config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get     '/lista',     to: "users#lista"
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to: 'static_pages#about'
  get     '/contact',   to: 'static_pages#contact'
  get     '/popular',   to: 'static_pages#popular'
  get     '/howtouse',   to: 'static_pages#howtouse'
  get     '/vision',    to: 'static_pages#vision'
  get     '/objetivos',    to: 'static_pages#objetivos'  
  get     '/candidate',    to: 'static_pages#candidate'   
  get     '/popular_last_day', to: 'static_pages#popular_last_day'
  get     '/signup',    to: 'users#new'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get     '/lista',     to: "users#lista"
  get     '/circles',   to: "users#following"
  get     '/new_plaza', to: 'users#new_plaza'
  get     '/plazas',    to: 'users#following_plaza'
  get     '/petition',  to: 'microposts#petition_form'
  get     '/micropost', to: 'microposts#show'
  get     '/petitions', to: 'microposts#petition_index'
  get     '/petitions_public', to: 'microposts#petition_index_public'
  post    '/plazas',            to: 'plazas#create'
  get     '/allplazas',         to: 'plazas#all_index'
  delete  '/dejardeseguir',     to: 'groups#destroy'
  post    '/seguir',            to: 'groups#create'
  get     '/popular',           to: 'static_pages#popular'
  get     '/index_municipios',  to: 'municipios#index'
  get     '/ir_a_tu_plaza',     to: 'plazas#show'

  resources :users do
    member do
      get :following, :followers
      get :edit_administrative
      put :update_administrative
      put :update_administrative_ciudad
      put :update_circles_administrative
    end

  resources :users do
    resources :users
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      get :hashtag
    end
  end
  resources :microposts do
    resources :comments do
      member do
        put :create
      end
    end
    resources :votes do
      member do
        put :update_like
        put :update_dislike
        put :update_circles_adminstrative
      end
    end
  end

  resources :users do
    resources :comments
    resources :plazas
    resources :groups
  end

  resources :plazas

  resources :municipios, only: [:index]
  
  resources :relationships,       only: [:create, :destroy]
end

app/models/plaza.rb
class Plaza < ApplicationRecord
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
  validates :name, presence: { message: "Please add a name" }, length: { maximum: 200 }, uniqueness: true
  mount_uploader :foto, PictureUploader
  validates :foto, presence: true
  validate  :picture_size

  has_many :microposts

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if foto.size > 2.megabytes
        errors.add(:foto, "should be less than 2MB")
      end
    end
end

app/controllers/plazas_controller.rb
class PlazasController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :index, :show, :new]
  before_action :correct_user,   only: :destroy

  require 'open-uri'

   def create
   	@user = current_user
    @plaza = @user.plazas.build(plaza_params)
    if @plaza.save
      flash[:success] = "Plaza created!"
      redirect_to  root_url
    else
      flash[:danger] = "No ha podido crearte, prueba con otro nombre y que no se te olvide la imagen!"
      redirect_back(fallback_location: new_user_plaza_path(current_user))
    end
  end

  def new
  	@plaza = Plaza.new
  end

  def index
    @user = User.find(params[:user_id])
    #Plazas seguidas por el usuario
    plaza_ids = "SELECT plaza_id FROM groups
                  WHERE  user_id = :user_id"
    # Select the post where user_id
    @plazas = Plaza.where("id IN (#{plaza_ids})       
                          OR user_id = :user_id", user_id: @user).paginate(page: params[:page], :per_page => 10)
  end

  def all_index
    @plazas = Plaza.all.paginate(page: params[:page])
    @plazas = if params[:tern]
      Plaza.where('name @@ :t or description @@ :t', t: params[:tern]).order('created_at DESC').paginate(page: params[:page])
    else
      Plaza.all.paginate(page: params[:page])
    end
  end

  def destroy
    @plaza.destroy
    flash[:success] = "Plaza deleted"
    redirect_to current_user.plaza
  end


  def show
    @user = User.find(params[:user_id])
    @plaza = Plaza.find(params[:id])
    @microposts = Micropost.where(:plaza_id => @plaza.id).paginate(page: params[:page])
    @peticiones = Micropost.where(:plaza_id => @plaza.id).where(:petition => true)
    @votos = Vote.where(:micropost_id => @microposts).where(:like == 1)
    @micropost  = current_user.microposts.build
    @group = current_user.groups.build
    @grupo_seguidores = Group.where(:plaza_id => @plaza.id)
    @grupo_seguidores.each do |seguidor|
      @seguidor = User.where(id: seguidor.user_id)
      @seguidor.each do |voter|
        @votos_seguidores = @votos.where(user_id: voter)
      end
    end
  end

  def index_actions
    @grupos = Group.where(user_id: current_user)
    @plazas = Plaza.where(action: true).where(id: @grupos.plaza_id)
  end

  private

    def plaza_params
      params.require(:plaza).permit(:name, :ciudad, :foto, :user_id, :description, :causa, :action, :administrative)
    end
    def correct_user
      @plaza = current_user.plazas.find_by(id: params[:id])
      redirect_to root_url if @plaza.nil?
    end

end

app/helpers/plazas_helper.rb
module PlazasHelper
end

app/views/plazas/_action_short.html.erb
<div class="aside_content" style="margin-top: 15px;">
  <ul class="principal">
    <li class="titulo">
      <% @usuario = params[:id] %>
      <% if @usuario != nil %>
        <ul style="padding: 0px; display: inline-flex;">
          <li style="border: 0px; display: inline-flex;">
            <i class="fa fa-bolt fa-lg" aria-hidden="true"></i>
            &nbsp;<h3 style="font-size: 16px; margin: 0px;"><b>Iniciativas</b></h3>
          </li>
          <li style="position: absolute; right: 30px; border: 0px;">
            <%= link_to "Ver todos", user_plazas_path(user_id: params[:id], accion: true) %>
          </li>
        </ul>
      <% else %>
        <ul style="padding: 0px; display: inline-flex;">
          <li style="border: 0px; display: inline-flex;">
            <i class="fa fa-bolt fa-lg" aria-hidden="true"></i>
            &nbsp;<h3 style="font-size: 16px; margin: 0px;"><b>Iniciativas</b></h3>
          </li>
          <li style="position: absolute; right: 30px; border: 0px;">
            <%= link_to "Ver todos", user_plazas_path(user_id: current_user, accion: true) %>
          </li>
        </ul>
      <% end %>
    </li>
    <% if @grupos_acciones != nil %>
      <% @grupos_acciones.each do |grupos_acciones| %>
        <% @plazas_acciones = Plaza.where(id: grupos_acciones.plaza_id) %>
        <% @actions = @plazas_acciones.where(action: true) %>
        <% @causas = @plazas_acciones.where(causa: true) %>

          <% @actions.take(5).each do |action| if @actions.any? %>
            <li class="lista_block">
              <ul class="inline">
                <li class="inline" style="align-items: center;">
                    <%= image_tag action.foto.url, size: 50, class: "img-circle" if action.foto? %>
                </li>
                <li style="padding-left: 10px; width: 78%;">
                  <b><%= link_to action.name, user_plaza_path(user_id: current_user, id: action) %></b>
                  <% @numero_seguidores = Group.where(plaza_id: action) %>
                  <span style="position: absolute; right: 25px;"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;<%= @numero_seguidores.count if @numero_seguidores.any? %></span>
                  <span style="display: inline-block;"><%= truncate(action.description, length: 100) %></span>
                </li>       
              </ul>
            </li>
          <% end %>
          <% end %>

      <% end %>
    <% end %>
  </ul>
</div>

app/views/plazas/_causa_short.html.erb
<div class="aside_content" style="margin-top: 15px;">
  <ul class="principal">
    <li class="titulo">
      <% @usuario = params[:id] %>
      <% if @usuario != nil %>
        <ul style="padding: 0px; display: inline-flex;">
          <li style="border: 0px; display: inline-flex;">
            <i class="fa fa-heart-o fa-lg" aria-hidden="true"></i>
            &nbsp;<h3 style="font-size: 16px; margin: 0px;"><b>Causas</b></h3>
          </li>
          <li style="position: absolute; right: 30px; border: 0px;">
            <%= link_to "Ver todos", user_plazas_path(user_id: params[:id], causa: true) %>
          </li>
        </ul>
      <% else %>
        <ul style="padding: 0px; display: inline-flex;">
          <li style="border: 0px; display: inline-flex;">
            <i class="fa fa-heart-o fa-lg" aria-hidden="true"></i>
            &nbsp;<h3 style="font-size: 16px; margin: 0px;"><b>Causas</b></h3>
          </li>
          <li style="position: absolute; right: 30px; border: 0px;">
            <%= link_to "Ver todos", user_plazas_path(user_id: current_user, causa: true) %>
          </li>
        </ul>
      <% end %>
    </li>
    <% if @grupos_acciones != nil %>
      <% @grupos_acciones.each do |grupos_acciones| %>
         <% @plazas_acciones = Plaza.where(id: grupos_acciones.plaza_id) %>
         <% @actions = @plazas_acciones.where(action: true) %>
         <% @causas = @plazas_acciones.where(causa: true) %>

        <% @causas.take(5).each do |causa| if @causas.any? %>
          <li class="lista_block">
            <ul class="inline">
              <li class="inline" style="align-items: center;">
                  <%= image_tag causa.foto.url, size: 50, class: "img-circle" if causa.foto? %>
              </li>
              <li class="inline" style="padding-left: 10px; width: 85%;">
                <span style="font-size: 15px;"><b><%= link_to causa.name, user_plaza_path(user_id: current_user, id: causa) %></b></span>
                <% @numero_seguidores = Group.where(plaza_id: causa) %>
                <span style="position: absolute; right: 25px; "><i class="fa fa-users" aria-hidden="true"></i>&nbsp;<%= @numero_seguidores.count if @numero_seguidores.any? %></span>
              </li>
            </ul>
          </li>
        <% end %>
        <% end %>

      <% end %>
    <% end %>
  </ul>
</div>

app/views/plazas/_plaza.html.erb
<li style="display: block;">
<ul style="list-style: none; padding-left: 0px; display: inline-flex; ">
  <li style="border: 0px; padding: 5px;">
    <%= image_tag plaza.foto.url, class: "img-circle", size: 50 if plaza.foto? %>
  </li>
  <li style="border: 0px; padding: 10px 0px;">
    <ul style="display: inline-block; list-style: none; padding-left: 5px;">
      <li style="padding: 0px;">
        Círculo <b><%= link_to plaza.name, user_plaza_path(id: plaza.id) %></b>
      </li>
      <li style="padding: 0px; border: 0px; font-size: 12px;">
        <%= @seguidores = Group.where(:plaza_id => plaza.id).count %> seguidores
        <% if logged_in? %>
          <% if current_user.admin? %>
          | <%= link_to "delete", plaza, method: :delete,
                                    data: { confirm: "You sure?" } %>
          <% end %>
        <% end %>
      </li>
    </ul>   
  </li>  
</ul>
</li>

app/views/plazas/_plaza_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%# @.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @seguidores.count %>
    </strong>
    followers
  </a>
</div>

app/views/plazas/_plazas_recomendadas.html.erb
<div>
	<% if logged_in? %>
	 <div class="usuarios_sugeridos" style="border: 1px solid #dddfe2; padding: 10px;">
	  <h3 style="margin: 0px;"><b><%= current_user.name %> hecha un vistazo a los siguientes lobbies:</b></h3>
	 </div>
	<% @usuarios = User.all %>
	<% if current_user.following(@usuario) %>
		<ul class="circulos_sugeridos">
			<% @usuarios.first(5).each do |user| %>
				<% @siguiendo_plaza = Group.where(user_id: user) %>
				<% @siguiendo_plaza.each do |siguiendo_plaza| %>
					<% @plazas_seguidas = Plaza.where(id: siguiendo_plaza.plaza_id) %>
					<% @plazas_seguidas = @plazas_seguidas.distinct %>
					<% @plazas_seguidas.each do |plaza_seguida| %>
						<% if plaza_seguida.administrative != true %>
							<% @grupos_seguidos_usuario = Group.where(user_id: current_user) %>
							<li style="display: block; border-bottom: 1px solid #e6e9ec;">
								<ul style="display: inline-flex; font-size: 13px;">
									<li class="imagen">
										<%= image_tag plaza_seguida.foto.url, class: "img-circle", size: 45 if plaza_seguida.foto? %>
									</li>
									<li class="texto">
										<% if plaza_seguida.action != true %>
            					<% if plaza_seguida.causa != true %>
                  			<i class="fa fa-circle-o" aria-hidden="true"></i>
                				<% else %>
                				<i class="fa fa-circle-o" aria-hidden="true"></i>
                				<% end %>
              			<% else %>		
                			<i class="fa fa-circle-o" aria-hidden="true"></i>
              			<% end %>
										&nbsp;<b><h3 style="margin: 0px; padding: 5px;  font-size: 15px;"><%= link_to plaza_seguida.name, user_plaza_path(id: plaza_seguida, user_id: current_user), style: "color: #1DA1F2;" %></b></h3>	
									</li>
								</ul>
							</li>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	</ul>
	<% end %>
</div>

app/views/plazas/show.html.erb
<div class="container">
  <% provide(:title, @plaza.name) %>
  <div class="row">
    <div class="col-sm-2">
      <!-- <div class="affix" style="width: 14%; max-width: 190px;"> -->
        <div class="plaza_stats">
          <div>
            <div class="background_img"></div>
            <ul class="plaza_name_img">
              <li>
                <ul>
                  <li>
                    <div class="plaza_img">
                      <%= image_tag @plaza.foto.url, class: "img-circle", size: 100  if @plaza.foto? %> 
                    </div>
                  </li>
                  <li class="texto">
                    <ul style="list-style: none; padding: 0px;">
                      <li>
                        <div class="plaza_name">
                          <h3 style="margin: 0px; font-weight: bolder; font-size: 22px;"><%= @plaza.name %></h3>
                        </div>
                      </li>
                      <% if @plaza.description? %>
                      <li class="description">
                        <%= @plaza.description %>
                      </li>
                      <% end %>                
                    </ul>
                  </li>                  
                </ul>
              </li>
              <li style="padding-top: 20px;">
                <%= render 'groups/seguir_form' if logged_in? %>
              </li>
            </ul>
          </div>
        </div>
        <div class="aside_content">
          <ul class="inline" style="margin-bottom: 0px;">
            <li class="titulo" style="align-items: center;"> 
              <% if @grupo_seguidores.where(user_id: current_user).any? %>              
                <%= link_to "Nueva consulta", petition_path(plaza: params[:id]), class: "btn btn-primary btn-sm" %>
              <% else %>
                Es necesario pertencer al cículo para realizar consultas en él, por favor, síguelo.
              <% end %>
            </li>
          </ul>
        </div>      
        <div class="aside_content">
          <ul class="principal" style="align-items: center;">
            <li class="titulo">
              Comunidad
            </li>
            <li style="width: 100%; text-align: center; color: #7e7e81;">
              <ul style="display: inline-flex; padding: 5px; width: 100%; ">
                <li style="width: 25%; border: none;">
                  <i class="fa fa-users" aria-hidden="true"></i>&nbsp;<%= link_to @grupo_seguidores.count, users_path(plaza_id: params[:id]) %>
                </li>
                <li style="width: 25%; border: none;">
                  <i class="fa fa-file-text-o" aria-hidden="true"></i>&nbsp;<%= @peticiones.count %>
                </li>
                <li style="width: 25%; border: none;">
                  <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                  <% if @microposts.any? %>
                     <%= @microposts.count %>
                  <% else %>
                     0
                  <% end %>
                </li>
                <li style="width: 25%; border: none;">
                  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>&nbsp;<%= @votos.count %>                
                </li>
              </ul>
            </li>
          </ul>
        </div>
      <!-- </div> -->
    </div>

    <div class="col-sm-4">

      <% if @plaza.administrative == true %>
        <div class="aside_content">
          <ul class="principal">
            <li class="titulo">
              <h5 style="margin: 0px; font-weight: 700;">Posicion del usuario dentro del círculo</h5>
            </li>
            <li class="inline">
              &nbsp;* No disponible. Es necesario ser afiliado para ser candidato
            </li>
          </ul>
        </div>
      <% end %>

      <div class="aside_content">
        <ul class="principal">
          <li class="titulo">
            <ul style="padding: 0px; display: inline-flex; width: 100%;">
              <li style="border: none; width: 80%;">
                <h5 style="margin: 0px; font-weight: 700;"><i class="fa fa-file-text-o" aria-hidden="true"></i> Resoluciones (más de 2/3 seguidores)</h5>
            <% @votos_seguidores.count if @votos_seguidores != nil %>
              </li>
              <li style="border: none; margin-right: -5px; text-align: right; width: 20%;">
                <div style="float: right; display: inline-flex; margin-top: 5px;">
                  <%= link_to "Ver todas", petitions_public_path(plaza_id: @plaza.id) %>
                </div>                
              </li>
            </ul>
            

          </li>
          <% @peticiones.each do |petition| %>
            <li class="lista_block">
              <ul class="inline" style="width: 65%;">
                <li class="inline">
                  <%= image_tag petition.picture.url, size: 55 if petition.picture? %>
                </li>
                <li class="inline" style="width: 100%;">
                  <span class="nombres" style="width: 100%;"><h5 style="margin: 0px; line-height: 20px;"><%= link_to petition.title, micropost_path(id: petition), style: "color: #444;" %></h5></span>
                </li>
                <li class="right" style="align-items: center;">
                  <%# porcentaje = porcetaje de votos emitidos por seguidores de la plaza, votos_seguidores / seguidores %>
                  <% @votos_seguidores = Vote.where(micropost_id: petition) %>
                  <% if @votos_seguidores.any? %>
                    <% @votos_seguidores.count %>
                    <% @votos_seguidores_positivos = @votos_seguidores.where(like: 1) %>
                    <% @votos_seguidores_positivos_porcentaje = @votos_seguidores_positivos.count * 100 / (@votos_seguidores.count) %>
                    <% if @votos_seguidores.any? %>
                      <% @porcentaje = (@votos_seguidores.count*100 / (@grupo_seguidores.count)) %>
                    <% else %>
                      <% @porcentaje = 0 %>
                    <% end %>

                    <% @valor_limite = 67 %>
                    <% @votos = Vote.where(:micropost_id => petition) %>
                    <% @votos = @votos.count %>
                    <% @grupo_seguidores.count %> 
                    <% @votos_seguidores.count %> 
                    <% @votos_seguidores_positivos.count %> 
                    <% @votos_seguidores_positivos_porcentaje %>
                    <% @porcentaje %>
                    <% (1*100/(2)) %> 
                 
                    <% if @porcentaje >= @valor_limite %>
                      <% if @votos_seguidores_positivos_porcentaje > 1/(2)*100 %>
                        <button type="button" class="btn btn-success" style="margin: 0px; font-size: 12px;">Aprobada <%= @porcentaje %><i class="fa fa-percent" aria-hidden="true"></i></button>
                      <% else %>
                        <button type="button" class="btn btn-danger" style="margin: 0px; font-size: 12px;">Denegada <%= @porcentaje %><i class="fa fa-percent" aria-hidden="true"></i></button>
                      <% end %>
                    <% else %>
                      &nbsp;<button type="button" class="btn btn-danger" style="background-color: white; border: 1px solid red; color: red; margin: 0px; font-size: 12px;">In progress <%= @porcentaje %><i class="fa fa-percent" aria-hidden="true"></i></button>
                    <% end %>
                  <% else %>
                    0 votos
                  <% end %>

                </li>
              </ul>
            </li>
          <% end %>

        </ul>
      </div>

      <div class="aside_content">
        <ul class="principal">
          <li class="titulo">
            <h5 style="margin: 0px; font-weight: 700;"><i class="fa fa-file-text-o" aria-hidden="true"></i> Iniciativas/Propuestas/Votaciones</h5>
          </li>
          <% if @peticiones.any? %>
          <% @peticiones.each do |petition| %>
          <li class="lista_block">
            <ul class="inline" style="width: 80%;">
              <li class="inline">
                <%= image_tag petition.picture.url, size: 50 if petition.picture? %>
              </li>
              <li class="inline" style="width: 100%;">
                  <span class="nombres" style="width: 100%;"><h5 style="margin: 0px; line-height: 20px;"><%= link_to petition.title, micropost_path(id: petition), style: "color: #444;" %></h5></span>
              </li>
              <li class="right" style="padding-top: 10px;">
                <% @votos = Vote.where(:micropost_id => petition) %>
                <% @votos_realizados = @votos.count %>
                <% if @votos_realizados != 0 %>
                <% @votos_positivos = @votos.where(:like => true).count %>
                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> (<%= @votos_positivos*100/(@votos_realizados) %> %)
                <% else %>
                  0 votos
                <% end %>
              </li>
            </ul>
            <% end %>
          <% else %>
          <div style="padding: 5px;">
            <% if @grupo_seguidores.where(user_id: current_user).any? %>              
              <%= link_to "Nueva consulta", petition_path(plaza: params[:id]), class: "btn btn-primary btn-sm" %>
            <% else %>
              Aún no hay consultas, pero es necesario pertencer al cículo para poder crearlas, por favor, únete.
            <% end %>
          </div>

          <% end %>
          </li>
        </ul>
      </div>

      <div class="aside_content">
        <ul class="principal">
          <li class="titulo">
            <h5 style="margin: 0px; font-weight: 700;"><i class="fa fa-users" aria-hidden="true"></i> Otros usuarios</h5>
          </li> 
            <%# if @grupo_seguidores != 0 %> 
            <% @grupo_seguidores.count %>
            <% @grupo_seguidores.each do |seguidor| %>
              <% @usuario = User.where(:id => seguidor.user_id) %>
              <% if @usuario.any? %>
                <% @usuario.each do |usuario| %>
                  <% if usuario != current_user %>
                  <li class="lista_block">
                    <ul class="inline" style="width: 80%;">
                      <li class="inline">
                        <%= image_tag usuario.foto.url, class: "img-rounded", size: 55 if usuario.foto? %>
                      </li>
                      <li class="inline" style="width: 100%;">
                        <span class="nombres" style="width: 100%;"><b><h5 style="margin: 0px; font-weight: 700;"><%= link_to usuario.name, usuario, style: "color: black;" %></b></span>
                      </li>
                      <li class="right">
                        <% if current_user.following?(usuario) %>
                          <button type="button" class="btn btn-light btn-sm" style="background-color: white;">Siguiendo</button>
                        <% else %>
                          <button type="button" class="btn btn-primary btn-sm" style="border-radius: 15px;"><%= link_to "Apoyar", usuario, {style: "color: white;"} %></button>
                        <% end %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              <% else %>
                No hay usuarios todavia.
              <% end %>
            <% end %>
            <%# end %>  
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-6">

      <h5 style="margin: 0px;"><b>Posts (<%= @microposts.count %>)</b></h5>
      <div>
       <%= render 'plazas/plaza_post_form'if logged_in? %>
      </div>

      <% if @microposts.any? %>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
      <% else %>
        El círculo <%= @plaza.name %> no tiene publicaciones. Sé el primero en publicar o mira los siguientes posts realizados en círculos relacionados.  
      <% end %>
    </div>

  </div>
</div>