config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get     '/lista',     to: "users#lista"
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to: 'static_pages#about'
  get     '/contact',   to: 'static_pages#contact'
  get     '/popular',   to: 'static_pages#popular'
  get     '/howtouse',   to: 'static_pages#howtouse'
  get     '/vision',    to: 'static_pages#vision'
  get     '/objetivos',    to: 'static_pages#objetivos'  
  get     '/candidate',    to: 'static_pages#candidate'   
  get     '/popular_last_day', to: 'static_pages#popular_last_day'
  get     '/signup',    to: 'users#new'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get     '/lista',     to: "users#lista"
  get     '/circles',   to: "users#following"
  get     '/new_plaza', to: 'users#new_plaza'
  get     '/plazas',    to: 'users#following_plaza'
  get     '/petition',  to: 'microposts#petition_form'
  get     '/micropost', to: 'microposts#show'
  get     '/petitions', to: 'microposts#petition_index'
  get     '/petitions_public', to: 'microposts#petition_index_public'
  post    '/plazas',            to: 'plazas#create'
  get     '/allplazas',         to: 'plazas#all_index'
  delete  '/dejardeseguir',     to: 'groups#destroy'
  post    '/seguir',            to: 'groups#create'
  get     '/popular',           to: 'static_pages#popular'
  get     '/index_municipios',  to: 'municipios#index'
  get     '/ir_a_tu_plaza',     to: 'plazas#show'

  resources :users do
    member do
      get :following, :followers
      get :edit_administrative
      put :update_administrative
      put :update_administrative_ciudad
      put :update_circles_administrative
    end

  resources :users do
    resources :users
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      get :hashtag
    end
  end
  resources :microposts do
    resources :comments do
      member do
        put :create
      end
    end
    resources :votes do
      member do
        put :update_like
        put :update_dislike
        put :update_circles_adminstrative
      end
    end
  end

  resources :users do
    resources :comments
    resources :plazas
    resources :groups
  end

  resources :plazas

  resources :municipios, only: [:index]
  
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # encoding: UTF-8
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :votes
  has_many :plazas
  has_many :groups
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  mount_uploader :foto, PictureUploader
  validates :foto, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
                          
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns a user's status feed.
  def feed
    # Returns a feed form following users
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    followers_ids = "SELECT follower_id FROM relationships
                     WHERE  followed_id = :user_id"
    #Plazas seguidas por el usuario
    plaza_ids = "SELECT plaza_id FROM groups
                WHERE  user_id = :user_id"
    #Select micropost votados por tus usuarios
    post_from_votes = "SELECT micropost_id FROM votes
                      WHERE :user_id IN (#{followers_ids})"
    # Select the post where user_id
    Micropost.where("user_id IN (#{following_ids})       
                     OR user_id = :user_id
                     OR plaza_id IN (#{plaza_ids})
                     OR id IN (#{post_from_votes})", user_id: id)
    
  end

  def feed_petition
    # Returns a feed form following users
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    followers_ids = "SELECT follower_id FROM relationships
                     WHERE  followed_id = :user_id"
    #Plazas seguidas por el usuario
    plaza_ids = "SELECT plaza_id FROM groups
                WHERE  user_id = :user_id"
    #Select micropost votados por tus usuarios
    post_from_votes = "SELECT micropost_id FROM votes
                      WHERE :user_id IN (#{followers_ids})"
    # Select the post where user_id
    Micropost.where(petition: true).where("user_id IN (#{following_ids})       
                     OR user_id = :user_id
                     OR plaza_id IN (#{plaza_ids})", user_id: id)
    
  end

  def petitions_public
    Micropost.where(petition: true).where("plaza_id is null")
  end

  def petitions
    Micropost.where("petition = true")
  end

  def petitions_all
    # Returns a feed form following users
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    followers_ids = "SELECT follower_id FROM relationships
                     WHERE  followed_id = :user_id"
    #Plazas seguidas por el usuario
    plaza_ids = "SELECT plaza_id FROM groups
                WHERE  user_id = :user_id"
    #Select micropost votados por tus usuarios
    post_from_votes = "SELECT micropost_id FROM votes
                      WHERE :user_id IN (#{followers_ids})"
    # Select the post where user_id
    Micropost.where(petition: true).where("user_id IN (#{following_ids})       
                     OR user_id = :user_id
                     OR plaza_id IN (#{plaza_ids})
                     OR plaza_id is null
                     OR id IN (#{post_from_votes})", user_id: id)    
  end
  
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def self.text_seach(query)
    if query.present?
      where("name @@ :q", q: "%#{query}")
    else
      scoped
    end
  end


  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers, :lista, :new_plaza, :plazas, :following_plaza, :show, :update_administrative,]
  before_action :correct_user,   only: [:edit, :update, :update_administrative]
  before_action :admin_user,     only: :destroy

  require 'open-uri'

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
    @users = if params[:tern]
      User.where('name @@ :t or description @@ :t', t: params[:tern]).order('created_at DESC').paginate(page: params[:page])
    else
      User.where(activated: true).paginate(page: params[:page])
    end
  end

  def plazas
    @users = User.where(plaza: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    @microposts = Micropost.where(:user_id => @user.id).paginate(page: params[:page], per_page: 10)
    @peticiones = Micropost.where(:user_id => @user.id).where(:petition => true)
    @peticiones_all = Micropost.where(:petition => true)
    @plazas_grupos = Group.where(:user_id => @user.id)
    # De acciones / causas / consultas _short
    @grupos_acciones = Group.where(user_id: @user)
    
    if @microposts.empty?
      @microposts = Micropost.where(:plaza_id => @user.id).paginate(page: params[:page], per_page: 10)
    else 
    end
    @comment = Comment.new( :micropost => @micropost )
    @micropost  = current_user.microposts.build 

  end

  def lista
    # Usuario que solo son de la ciudad del user
    users_ciudad = ("SELECT id FROM users
                    WHERE ciudad = :ciudad")

    @candidatos_pueblo = User.find_by_sql(
      'SELECT     users.id,
      COUNT       (relationships.followed_id)
      AS          numbersOfFollowers
      FROM        relationships
      LEFT JOIN   users
      ON          relationships.followed_id = users.id
      GROUP BY    users.id
      ORDER BY    count(followed_id) 
      DESC
      ') 
    @candidatos_autonomia = User.find_by_sql(
      'SELECT     users.id,
      COUNT       (relationships.followed_id)
      AS          numbersOfFollowers
      FROM        relationships
      LEFT JOIN   users
      ON          relationships.followed_id = users.id
      GROUP BY    users.id
      ORDER BY    count(followed_id) 
      DESC
      ')
    @candidatos_mundo = User.find_by_sql(
      'SELECT     users.id,
      COUNT       (relationships.followed_id)
      AS          numbersOfFollowers
      FROM        relationships
      LEFT JOIN   users
      ON          relationships.followed_id = users.id
      GROUP BY    users.id
      ORDER BY    count(followed_id) 
      DESC
      ')
  end

  def new
    @user = User.new
  end

  def new_plaza
    @plaza = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to  :back #root_url 
    else
      render 'new'
    end
  end

  def create_plaza
    @user = User.new(plaza_params)
    if @user.save
      flash[:info] = "Added new plaza!!"
      redirect_to  '/plazas' 
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def edit_administrative
    @user = User.find(params[:id])
  end

  def update_administrative
    @user = User.find(params[:id])
    if @user.update_attributes(autonomia: params[:autonomia], provincia: params[:provincia], ciudad: params[:ciudad])
      respond_to do |format|
        format.html { 
          redirect_back fallback_location: root_url 
        }
        format.js
      end
    else
    end
  end

  def update_administrative_ciudad
    @user = User.find(params[:id])
    if @user.update_attributes(ciudad: params[:ciudad], provincia: params[:provincia])
      respond_to do |format|
        format.html { 
          redirect_back fallback_location: root_url 
        }
        format.js
      end
    else
    end
  end

  def update_circles_administrative
    @user = User.find(params[:id])
    if @user.update_attributes(ciudad: params[:ciudad])
      flash[:success] = "Círculos actualizados!"
      redirect_to root_url
    else
      redirect_back fallback_location: root_url
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to edit
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'following'
  end

  def following_plaza
    @user = current_user
    @title = "Your Plazas"
    @users = @user.following.where(:plaza => true).paginate(page: params[:page])
    render 'following'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :ciudad, :autonomia, :profesion, :foto, :created_by, :plaza, :linkedin, :description, :provincia, :pais, :tern, :candidate)
    end

    def plaza_params
      params.require(:user).permit(:activated, :name, :email, :password,
                                   :password_confirmation, :ciudad, :autonomia,:profesion, :foto, :created_by, :plaza)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Apoyar", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_provincia.html.erb
<div id="formulario">
	<%= form_tag(update_administrative_ciudad_user_path(current_user), remote: true, method: :put) do |f| %>
	    <%# render 'shared/error_messages', object: f.object %>
	    <%# @autonomia = Comunidad.where(comunidad: current_user.autonomia).first %>
			<%# @provincias = Provincia.where(comunidad_id: @autonomia.id) %>
	  	
	    <%= select_tag(:provincia, options_for_select(Provincia.all.collect {|p| [ p.provincia ]} )) %>
	    <%= submit_tag "Save changes", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/users/lista.html.erb
<% provide(:title, 'Ranks') %>
	<div class="container">
    <div class="row">
      <aside class="col-sm-2">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%# render 'shared/stats' %>
        </section>
      </aside> 
  		<div class="col-sm-7" style="padding-right: 5px; padding-left: 5px;">
  			<div style="background-color: white; padding: 15px; margin-bottom: 20px; padding-bottom: 10px;">
	  			<h3 style="margin: 0px;">Candidatos</h3>
	  			<h5>Una lista con los 20 candidatos con mayor número de afiliados en cada lobby administrativo.</h5>  				
  			</div>

  			<!--<div class="instrucciones">
  				 Representantes de cada círculo administrativo. Los candidatos son aquellos que tienen una mayor compromiso dentro del círculo, expresada en número de seguidores pero también en forma de propuestas y votos.  
  			</div>-->
				<ul style="list-style: none; padding-left: 0px;">

					<li style="width: 100%;">
						<li style="background-color: white; padding: 10px; border-bottom: 1px solid #e6e6e6;">
							<h3 style="margin: 5px;"><b>Candidatos en <%= current_user.ciudad %></b></h3><div style="text-align: right;"></div>
						</li>
							<% if @candidatos_pueblo.any? %>
								<% @candidatos_pueblo.first(20).each do |x| %>
									<% @user = User.where(:id => x.id).where(:ciudad => current_user.ciudad) %>
								    <%  @user.each do |candidate| %>
								    	<% if candidate.candidate == true %>
										    <ul class="candidate_list" style="padding-left: 20px;">
										    	
										    	<li style="padding-top: 10px;">
										    		<%= image_tag candidate.foto.url, class: "img-circle", size: 55 if candidate.foto? %>
										    	</li>
										    	<li style="width: 60%;">
										    		<ul class="texto">
										    			<li style="">
											    			<h3 style="margin: 0px; font-size: 16px;"><b><%= link_to candidate.name, candidate %></b><span style="font-size: 13px;"> (#<%= @candidatos_pueblo.index(candidate) + 1 %>)</span></h3>
											    		</li>
											    		<li style="font-size: 13px;">
											    			<b><%= candidate.followers.count %> seguidores.</b>
											    		</li>

											    			<% @plaza_votos = Plaza.find_by(:name => current_user.ciudad) %>
											    		<% if @plaza_votos != nil %>
													    	<% @post_plaza = Micropost.where(:plaza_id => @plaza_votos.id).where(:user_id => candidate.id) %>
													    	<% @post_plaza_petition = @post_plaza.where(:petition => true) %>
													    	<li style="font-size: 13px; color: #8c8c8c; width: 90%;">
													    		<span style="font-weight: normal;"><%= @votos = Vote.where(:micropost_id => @post_plaza).count %> votos en <%= current_user.ciudad %>.</span>

													    	</li>
													    	<li style="font-size: 13px; color: #8c8c8c; width: 90%;">
													    		<span style="font-weight: normal;"><%= @post_plaza_petition.count %> iniciativas en <%= current_user.ciudad %>.</span>
													    	</li>
												    	<% else %>
												    		
												    		<div class="sigue_plaza" style="border-radius: 5px; padding: 5px; font-size: 13px; border: 2px solid #f4ac41; margin-top: 20px;">
																	El círculo no está creado aún <%= link_to "Créalo", new_user_plaza_path(current_user, name: current_user.provincia)  %>
																</div> 
												    	<% end %>
											    	</ul>
											    </li>
											   	<li>
											    	<ul style="display: inline-flex; width: 100%;">
												    	<li style="position: absolute; right: 20px; ">
														    <% if current_user.following?(candidate) %>
														    	<button type="button" class="btn btn-default btn-sm"><span style="font-size: 13px;">Siguiendo</span></button>
														    <% else %>
																	<button type="button" class="btn btn-primary btn-sm"><span style="font-size: 13px;"><%= link_to "Apoyar", candidate, {style: "color: white"} %></span></button>
														    <% end %>
													  	</li>
											    	</ul>
											    </li>
										    </ul>
									    <% end %>
								    <% end %>
								<% end %>
							<% end %>
					</li>

					<li style="width: 100%;">
						<li style="background-color: white; padding: 10px; border-bottom: 1px solid #e6e6e6; margin-top: 20px;">
							<h3 style="margin: 5px;"><b>Candidatos en <%= current_user.autonomia %></b></h3>
						</li>
								<% @candidatos_autonomia.take(20).each do |x| %>
									<% @user = User.where(:id => x.id).where(:autonomia => current_user.autonomia) %>
								    <%  @user.each do |candidate| %>
								    	<% if candidate.candidate == true %>
									    	<ul class="candidate_list" style="padding-left: 20px;">
									    	<li style="padding-top: 10px;">
									    		<%= image_tag candidate.foto.url, class: "img-circle", size: 55 if candidate.foto? %>
									    	</li>
									    	<li style="width: 60%;">
									    		<ul class="texto">
									    			<li  style="width: 90%;">
										    			<h3 style="margin: 0px; font-size: 16px;"><b><b><%= link_to candidate.name, candidate %></b><span style="font-size: 13px;"> (#<%= @candidatos_autonomia.index(candidate) + 1 %>)</span></h3>
										    		</li>
										    		<li style="font-size: 13px;">
										    			<b><%= candidate.followers.count %> seguidores.</b>
										    		</li>
										    			<% @plaza_votos = Plaza.find_by(:name => current_user.autonomia) %>

											    	<% if @plaza_votos != nil %>
											    		<% @post_plaza = Micropost.where(:plaza_id => @plaza_votos.id).where(:user_id => candidate.id) %>
											    		<% @post_plaza_petition = @post_plaza.where(:petition => true) %>
											    		<li style="font-size: 13px; color: #8c8c8c; width: 90%;">
											    			<span style="font-weight: normal;"><%= @votos = Vote.where(:micropost_id => @post_plaza).count %> votos en <%= current_user.autonomia %>.</span>

											    		</li>
											    		<li style="font-size: 13px; color: #8c8c8c; width: 90%;">
											    			<span style="font-weight: normal;"><%= @post_plaza_petition.count %> iniciativas en <%= current_user.autonomia %>.</span>
											    		</li>
											    	<% else %>
											    		 
											    		<div class="sigue_plaza" style="border-radius: 5px; padding: 5px; font-size: 13px; border: 2px solid #f4ac41; margin-top: 20px;">
																El círculo no está creado aún <%= link_to "Créalo", new_user_plaza_path(current_user, name: current_user.provincia)  %>
															</div> 
											    	<% end %>
										    	</ul>
										    </li>
										   	<li>
										    	<ul style="display: inline-flex; width: 100%;">
											    	<li style="position: absolute; right: 20px; ">
													    <% if current_user.following?(candidate) %>
													    	<button type="button" class="btn btn-default btn-sm"><span style="font-size: 13px;">Siguiendo</span></button>
													    <% else %>
																<button type="button" class="btn btn-primary btn-sm"><span style="font-size: 13px;"><%= link_to "Apoyar", candidate, {style: "color: white"} %></span></button>
															<% end %>
												  	</li>
										    	</ul>
										    </li>
									    	</ul>
									    <% end %>
								    <% end %>
								<% end %>
					</li>
					
					<li style="width: 100%;">
						<li style="background-color: white; padding: 10px; border-bottom: 1px solid #e6e6e6; margin-top: 20px;">
							<h3 style="margin: 5px;">Candidatos en España</h3>
						</li>
								<% @candidatos_mundo.take(20).each do |x| %>
									<% @user = User.where(:id => x.id) %>
								    <% @user.each do |candidate| %>
								    	<% if candidate.candidate == true %>
										    <ul class="candidate_list" style="padding-left: 20px;">
										    	<li style="padding-top: 10px;">
										    		<%= image_tag candidate.foto.url, class: "img-circle", size: 55 if candidate.foto? %>
										    	</li>
										    	<li style="width: 60%;">
										    		<ul class="texto">
										    			<li style="width: 90%;">
											    			<h3 style="margin: 0px; font-size: 16px;"><b><b><%= link_to candidate.name, candidate %></b> <span style="font-size: 13px;">(#<%= @candidatos_mundo.index(candidate) + 1 %>)</span> </h3>
											    		</li>
											    		<li style="font-size: 13px;">
											    			<b><%= candidate.followers.count %> seguidores.</b>
											    		</li>
											    		<li style="font-size: 13px;  color: #8c8c8c; width: 90%;">
											    			<% @post_plaza = Micropost.where(:user_id => candidate.id) %>
											    			<% @post_plaza_petition = @post_plaza.where(:petition => true) %>
										    				<span style="font-weight: normal;"><%= @votos = Vote.where(:micropost_id => @post_plaza).count %> votos.</span>
												    	</li>
												    	<li style="font-size: 13px; color: #8c8c8c; width: 90%;">
												    		<span style="font-weight: normal;"><%= @post_plaza_petition.count %> iniciativas.</span>
												    	</li>
											    	</ul>
											    </li>
											   	<li>
											    	<ul style="display: inline-flex; width: 100%;">
												    	<li style="position: absolute; right: 20px; ">
														    <% if current_user.following?(candidate) %>
														    	<button type="button" class="btn btn-default btn-sm"><span style="font-size: 13px;">Siguiendo</span></button>
														    <% else %>
																	<button type="button" class="btn btn-primary btn-sm"><span style="font-size: 13px;"><%= link_to "Apoyar", candidate, {style: "color: white"} %></span></button>
																<% end %>
													  	</li>
											    	</ul>
											    </li>
										    </ul>
									    <% end %>
								    <% end %>
								<% end %>
					</li>

				</ul>
			</div>

			<aside>
			  <div class="col-sm-3">
			  	<!--<div class="affix" style="width: 20%;">-->
					  	<div class="usuarios_sugeridos">
					  		<div style="border-bottom: 1px solid #e6e9ec; padding: 10px;">
						      <h5 style="margin: 0px; line-height: 18px;"><b><%= current_user.name %> los siguientes candidatos buscan tu apoyo:</b></h5>
						    </div>
					    	<% @tus_grupos = Group.where(user_id: current_user) %>
					  		<% @tus_grupos.first(5).each do |tus_grupos| %>
					    		<% @users_grupos = Group.where(plaza_id: tus_grupos.plaza_id) %>
					    			<% @users_grupos.first(3).each do |users_grupos| %>
					      			<% @users_plazas = User.where(id: users_grupos.user_id) %>
					      			<% @plazas_users = Plaza.where(id: users_grupos.plaza_id) %>
					      			<% @plazas_users.first(3).each do |plazas_users| %>
					      			<% @users_plazas.first(3).each do |users_plazas| %>
					      				<% unless current_user.following?(users_plazas) %>
						      				<% if users_plazas != current_user %>
							      				<% if plazas_users.name != current_user.autonomia %>
								      				<% if users_plazas.candidate == true %>
									  						<li>
									  							<ul class="texto" style="display: inline-flex; align-items: center;">
												  					<li style="display: block; padding: 5px;">
											  							<%= image_tag (users_plazas.foto.url), class: "img-circle", size: 45 if users_plazas.foto? if users_plazas != current_user %> 
											  						</li>
											  						<li style="padding-left: 5px;">
												  						<h5 style="margin: 0px; font-weight: normal; display: inline-flex; font-weight: bold; line-height: 18px;"> <%= link_to users_plazas.name, users_plazas %></h5> 
												  						 en <i class="fa fa-circle-o" aria-hidden="true"></i>&nbsp;<h5 style="margin: 0px; font-weight: normal; display: inline-flex; font-weight: bold;"><%= link_to plazas_users.name, user_plaza_path(user_id: current_user, id: plazas_users) %></h5>
											    						<%# image_tag (plazas_users.foto.url), class: "img-circle", size: 45 if plazas_users.foto? if users_plazas != current_user %>
											    					</li>
									  							</ul>
									  						</li>
									  					<% end %>
								  					<% end %>
							  					<% end %>
					      				<% end %>
					      			<% end %>
					      			<% end %>
					    		<% end %>
					  		<% end %>  		
					  	</div>

					  	</div>  	
			  	<!--</div>-->
				</div>
	    </aside>
		</div>
	</div>

app/views/users/update_administrative.js.erb
$("#formulario").html("<%= escape_javascript(render('users/provincia')) %>");

app/views/users/update_administrative_ciudad.js.erb
$("#formulario").html("<%= escape_javascript(render('users/ciudad')) %>");