config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get     '/lista',     to: "users#lista"
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to: 'static_pages#about'
  get     '/contact',   to: 'static_pages#contact'
  get     '/popular',   to: 'static_pages#popular'
  get     '/howtouse',   to: 'static_pages#howtouse'
  get     '/vision',    to: 'static_pages#vision'
  get     '/objetivos',    to: 'static_pages#objetivos'  
  get     '/candidate',    to: 'static_pages#candidate'   
  get     '/popular_last_day', to: 'static_pages#popular_last_day'
  get     '/signup',    to: 'users#new'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get     '/lista',     to: "users#lista"
  get     '/circles',   to: "users#following"
  get     '/new_plaza', to: 'users#new_plaza'
  get     '/plazas',    to: 'users#following_plaza'
  get     '/petition',  to: 'microposts#petition_form'
  get     '/micropost', to: 'microposts#show'
  get     '/petitions', to: 'microposts#petition_index'
  get     '/petitions_public', to: 'microposts#petition_index_public'
  post    '/plazas',            to: 'plazas#create'
  get     '/allplazas',         to: 'plazas#all_index'
  delete  '/dejardeseguir',     to: 'groups#destroy'
  post    '/seguir',            to: 'groups#create'
  get     '/popular',           to: 'static_pages#popular'
  get     '/index_municipios',  to: 'municipios#index'
  get     '/ir_a_tu_plaza',     to: 'plazas#show'

  resources :users do
    member do
      get :following, :followers
      get :edit_administrative
      put :update_administrative
      put :update_administrative_ciudad
      put :update_circles_administrative
    end

  resources :users do
    resources :users
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      get :hashtag
    end
  end
  resources :microposts do
    resources :comments do
      member do
        put :create
      end
    end
    resources :votes do
      member do
        put :update_like
        put :update_dislike
        put :update_circles_adminstrative
      end
    end
  end

  resources :users do
    resources :comments
    resources :plazas
    resources :groups
  end

  resources :plazas

  resources :municipios, only: [:index]
  
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_circulo_info.html.erb
<%= image_tag current_user.foto.url, class: "img-rounded", size: 150 if current_user.foto? %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span class="badge"><%#  pluralize(current_user.microposts.count, "micropost") %></span>

<ul style="list-style: none; padding-left: 0px; ">
	<li style="border-bottom: 1px solid  #e6e6e6; border-top: 1px solid #e6e6e6;">
		<!-- Pueblos -->
		<h6 style="margin-bottom: 2px;">Círculo Municipal:</h6>
		<% @pueblo = Plaza.where(:name => current_user.ciudad) %>
			<% if @pueblo.any? %>	
				<% @pueblo.each do |pueblo| %>
					<h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag pueblo.foto.url, class: "img-circle", size: 40 if pueblo.foto? %>  <%= link_to pueblo.name, user_plaza_path(:id => pueblo.id, :user_id => current_user.id) %></h5>
					<% end %>
			<% else %>
				<div class="sigue_plaza" style="background-color: #ffffcc; border-radius: 5px; padding: 0px 0px; font-size: 12px;">
					<%= link_to "Crea el círculo", new_user_plaza_path(current_user)  %>
				</div>
			<% end %>
	</li>

	<li style="border-bottom: 1px solid #e6e6e6">
		<!-- Autonomia -->
		<h6 style="margin-bottom: 2px;">Círculo autonómico</h6>
		<% @autonomia = Plaza.where(:name => current_user.autonomia) %>
		<% if @autonomia.any? %>	
				<% @autonomia.each do |autonomia| %>
					<h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag autonomia.foto.url, class: "img-circle", size: 40 if autonomia.foto? %>  <%= link_to autonomia.name, user_plaza_path(:id => autonomia.id, :user_id => current_user.id) %></h5>
					<% end %>
			<% else %>
				<div class="sigue_plaza" style="background-color: #ffffcc; border-radius: 5px; padding: 0px 0px; font-size: 12px;">
					Crea el círculo <h4 style="margin: 0px;"><%= link_to current_user.autonomia, new_user_plaza_path(current_user) %></h4>
				</div>
			<% end %>
	</li>

	<li style="border-bottom: 1px solid #e6e6e6">
		<!-- Profesion -->
		<h6 style="margin-bottom: 2px;">Círculo Profesional</h6>
		<% @profesion = Plaza.where(:name => current_user.profesion) %>
		<% if @profesion.any? %>	
				<% @profesion.each do |profesion| %>
					<h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag profesion.foto.url, class: "img-circle", size: 40 if profesion.foto? %>  <%= link_to profesion.name, user_plaza_path(:id => profesion.id, :user_id => current_user.id) %></h5>
					<% end %>
			<% else %>
				<div class="sigue_plaza" style="background-color: #ffffcc; border-radius: 5px; padding: 0px 0px; font-size: 12px;">
					Crea el círculo <h4 style="margin: 0px;"><%= link_to current_user.profesion, new_user_plaza_path(current_user) %></h4>
				</div>
			<% end %>
	</li>

	<li style="border-bottom: 1px solid #e6e6e6">
		<!-- Otras plazas -->
		<h6 style="margin-bottom: 2px;">Todas tus plazas</h6>
		<% @grupos = Group.where(:user_id => current_user.id) %>
		<ul style="list-style: none; padding-left: 0px;">
			<% @grupos.each do |grupo| %>
			<% @plazas_seguidas = Plaza.where(:id => grupo.plaza_id) %>
			<% @plazas_seguidas.each do |plaza_seguida| %>
				<li style="display: inline-flex;">
				<%= image_tag plaza_seguida.foto.url, class: "img-circle", size: 40 if plaza_seguida.foto? %>
				<h5 style="font-size: 12px; padding-top: 4px; padding-left: 5px;"><%= link_to plaza_seguida.name, user_plaza_path(:id => plaza_seguida.id, :user_id => current_user.id) %></h5>
				</li>
			<% end %>
		<% end %>
		</ul>
	</li>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_lista.html.erb
<h5><b><%= current_user.ciudad %></b></h5>
<div class="candidates_home">
	<ul>
		<% if @candidates != nil %>	
			<% @candidates.take(10).each do |candidate| %>
				<% @candidate = User.where(:id => candidate.id).where(:ciudad => current_user.ciudad) %>
				<% @candidate.each do |candidate2| %>
					<ul style="display: inline-flex;">
						<li>
							<%= image_tag candidate2.foto.url, class: "img-circle", size: 40 if candidate2.foto? %>	
						</li>
						<ul style="display: inline-block;">
							<li style="padding-top: 3px; padding-left: 3px; font-size: 12px; margin-bottom: 0px;">
								<b><%= link_to candidate2.name, candidate2 %></b>
							</li>
							<li style="font-size: 11px; margin-top: 0px; padding-left: 3px;">
								<%= candidate2.followers.count %> seguidores
							</li>
						</ul>
					</ul>
				<% end %>
			<% end %>
		<% end %>
	</ul>	
</div>

<h5><b><%= current_user.autonomia %></b></h5>
<div class="candidates_home">
	<ul>
		<% if @candidates != nil %>		
			<% @candidates.take(10).each do |candidate| %>
				<% @candidate = User.where(:id => candidate.id).where(:autonomia => current_user.autonomia) %>
				<% @candidate.each do |candidate2| %>
					<ul style="display: inline-flex;">
						<li>
							<%= image_tag candidate2.foto.url, class: "img-circle", size: 40 if candidate2.foto? %>	
						</li>
						<ul style="display: inline-block;">
							<li style="padding-top: 3px; padding-left: 3px; font-size: 12px; margin-bottom: 0px;">
								<b><%= link_to candidate2.name, candidate2 %></b>
							</li>
							<li style="font-size: 11px; margin-top: 0px; padding-left: 3px;">
								<%= candidate2.followers.count %> seguidores
							</li>
						</ul>
					</ul>
				<% end %>
			<% end %>
		<% end %> 
	</ul>	
</div>





app/views/shared/_micropost_form.html.erb
<span class="emoticons">
    <div style="width: 100%; background-color: #f2f4ff;">
        <ul class="" style="display: inline-flex; list-style: none; text-align: center; width: 70%; padding-left: 0px; padding-top: 5px; margin-bottom: 5px;">
            <!-- <li style="width: 25%; background-color: #c2d7f9; padding: 10px;";"><i class="fa fa-paper-plane-o fa-lg" aria-hidden="true"></i><span> Posts</span></li> --> 
            <li style="width: 40%; border-right: 1px solid #d9d9d9;" onclick="divVisibility('Div1');"><i class="fa fa-newspaper-o fa-lg" aria-hidden="true" style="color: #0084B4;"></i><span> Add a Link</span></li>  
            <li style="width: 30%; border-right: 1px solid #d9d9d9;" onclick="divVisibility('Div2');"><i class="fa fa-youtube fa-lg" aria-hidden="true" style="color: red;"></i><span> Video</span></li>
            <li style="width: 30%;" onclick="divVisibility('Div3');"><i class="fa fa-picture-o fa-lg" aria-hidden="true" style="color: green;"></i><span> Imagen</span></li>
        </ul>        
    </div>

</span>

<!-------------------------------------------------------- -->
<!-- Formulario del micropost -->
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
        <div class="share-content">
            <ul style="list-style-type: none; -webkit-padding-start: 5px; margin: 0px; border-bottom: 1px solid #f2f2f2;">
                <li style="display: inline-flex; margin-top: 10px;">
                    <%= image_tag (current_user.foto.url), class: "img-circle", size: 25 if current_user.foto? %>
                </li>
                <li style="display: inline-flex; width: 90%; margin: 0px;">
                    <%= f.text_area :content, placeholder: " Share something with the community..." %>
                </li>

            </ul>
            <ul style="display: inline-flex; list-style-type: none; width: 100%; margin: 0px; padding-left: 0px;">
                    <li style="padding-top: 8px; width: 60%; margin-left: 5px; margin-right: 15px; display: inline-flex;">
                        <i class="fa fa-comments-o" style="font-size: 16px;"></i>&nbsp;
                        <%= f.text_field :hashtag1, placeholder: " Hashtag...", style: "margin-bottom: 5px; border: none; font-size: 12px;", maxlength: 12 %>
                    </li>
                    <li style="width: 30%; padding-top: 5px; font-size: 11px;" >
                        <%= f.hidden_field :petition, :value => false %>
                        <%= f.hidden_field :hashtag2, :value => "posts" %>
                        <%= f.submit "Post", class: "btn btn-info btn-sm", style: "background-color: #c2d7f9; color: black; border: 0px; margin-bottom: 5px;" %> 
                    </li>
                </ul>
        </div>

    <div id="Div1" style="display: none;">
        <div class="share-content">
            <div class="iconos-share">
                <ul style="display: inline-flex; list-style-type: none; width: 100%; margin-bottom: 3px; padding-left: 5px;">
                    <li style="width: 100%; display: inline-flex;">
                        <i class="fa fa-newspaper-o fa-lg" aria-hidden="true" style="padding: 8px;"></i>
                        <%= f.text_field :link, placeholder: "  Pega el enlace directamente de la barra de direcciones", style: "margin-bottom: 3px;" %>

                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div id="Div2" style="display: none; ">
        <div class="share-content">
            <div class="iconos-share">
                <ul style="display: inline-flex; list-style-type: none; width: 100%; margin-bottom: 3px;  padding-left: 5px;">
         
                    <li style="width: 100%; display: inline-flex;">
                        <i class="fa fa-video-camera fa-lg" aria hidden="true" style="padding: 8px;"></i>
                        <%= f.text_field :video, placeholder: "  O quizá un video. Copia el codigo del video de Youtube", style: "margin-bottom: 3px;" %>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div id="Div3" style="display: none; "> 
        <div class="share-content">
            <div class="iconos-share">
                <ul style="display: inline-flex; list-style-type: none; width: 100%; margin-bottom: 3px; padding-left: 15px;">
                    <li style="padding: 0px; width: 100%; margin-left: 10px;">
                        <div id="test">
                            <div class="wrapper" style="margin-top: 5px; padding-bottom: 10px; height: 30px;">
                                <%= f.file_field(:picture, accept: 'image/jpeg,image/gif,image/png',  class: 'file_input') %>
                            </div>
                            <button class= "btn btn-default btn-sm"><span class="fa fa-picture-o fa-lg" aria-hidden="true"></span> Image </button>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

<% end %>

<script>
 var divs = ["Div1", "Div2", "Div3"];
    var visibleDivId = null;
    function divVisibility(divId) {
      if(visibleDivId === divId) {
        visibleDivId = null;
      } else {
        visibleDivId = divId;
      }
      hideNonVisibleDivs();
    }
    function hideNonVisibleDivs() {
      var i, divId, div;
      for(i = 0; i < divs.length; i++) {
        divId = divs[i];
        div = document.getElementById(divId);
        if(visibleDivId === divId) {
          div.style.display = "block";
        } else {
          div.style.display = "none";
        }
      }
    }
</script>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
      alert('Maximum file size is 2MB. Please choose a smaller file.');
    }
  });
</script>

<!-- fin del formulario del post -->

<!-- fin colapsable -->

app/views/shared/_plazas_info.html.erb
<% @posts = Micropost.where(:user_id => current_user.id) %>
<% @peticiones = Micropost.where(:user_id => current_user.id).where(:petition => true) %>
<% @peticiones_all = Micropost.where(:petition => true) %>
<% @plazas_grupos = Group.where(:user_id => current_user.id) %>

<div class="plazas_info">
  <ul>
    <% if current_user.autonomia? %>
    	<li>
    		<!-- Pueblos -->
    		<span>Círculo Municipal:</span>
        <% current_user.ciudad if current_user.ciudad %>
    		<%  %>
    			<% if (@pueblo = Plaza.where(:name => current_user.ciudad)).any? %>	
    				<% @pueblo.each do |pueblo| %>
    					<h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag pueblo.foto.url, class: "img-circle", size: 40 if pueblo.foto? %>  <b><%= link_to pueblo.name, user_plaza_path(:id => pueblo.id, :user_id => current_user.id) %></b></h5>
    					<% end %>
    			<% else %>
    				<div class="sigue_plaza">
    					El círculo aún no está creado, <%= link_to "Sé el primero", new_user_plaza_path(current_user, name: current_user.ciudad) %>
    				</div>
    			<% end %>
    	</li>

      <li>
        <!-- Provincia -->
        <span style="margin-bottom: 2px;">Círculo Provincial:</span>
        <% current_user.provincia if current_user.provincia? %>
          <% if (@provincia = Plaza.where(:name => current_user.provincia)).any? %> 
            <% @provincia.each do |provincia| %>
              <h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag provincia.foto.url, class: "img-circle", size: 40 if provincia.foto? %>  <b><%= link_to provincia.name, user_plaza_path(:id => provincia.id, :user_id => current_user.id) %></b></h5>
              <% end %>
          <% else %>
            <div class="sigue_plaza">
              El círculo aún no está creado, <%= link_to "Sé el primero", new_user_plaza_path(current_user, name: current_user.provincia) %>
            </div>
          <% end %>
      </li>

    	<li>
    		<!-- Autonomia -->
    		<span style="margin-bottom: 2px;">Círculo autonómico</span>
        <% current_user.autonomia if current_user.autonomia %>

    		<% if (@autonomia = Plaza.where(name: current_user.autonomia)).any?  %>
    				<% @autonomia.each do |autonomia| %>
    					<h5 style="margin-top: 2px; font-size: 12px;padding-left: 5px;"><%= image_tag autonomia.foto.url, class: "img-circle", size: 40 if autonomia.foto? %> <b><%= link_to autonomia.name, user_plaza_path(:id => autonomia.id, :user_id => current_user.id) %></b></h5>
    					<% end %>
    			<% else %>
    				<div class="sigue_plaza">
    					El círculo aún no está creado, <%= link_to "Sé el primero", new_user_plaza_path(current_user, name: current_user.autonomia) %>
    				</div>
    			<% end %>
    	</li>
    <% else %>
      <div class="instrucciones">
        No tienes marcadas tus círculos administrativos. Márcalos para acceder a las listas electorales y participar de las decisiones que se toman en tus círculos.
        <%= link_to "Participa", edit_administrative_user_path(id: current_user), class: "btn btn-primary" %>
      </div>
    <% end %>

  	<li>
  		<!-- Otras plazas -->
  		<span>Todas tus plazas</span>
  		<% @grupos = Group.where(:user_id => current_user.id) %>
      <% if @grupos.any? %>
  			<% @grupos.each do |grupo| %>
  			<% @plazas_seguidas = Plaza.where(:id => grupo.plaza_id).where.not(name: current_user.ciudad).where.not(name: current_user.provincia).where.not(name: current_user.autonomia) %>
    			<% @plazas_seguidas.each do |plaza_seguida| %>
    				<li style="display: inline-flex; align-items: center;">
    				<%= image_tag plaza_seguida.foto.url, class: "img-circle", size: 40 if plaza_seguida.foto? %>
    				<h5 style="font-size: 12px; padding-top: 4px; padding-left: 5px;"><b><%= link_to plaza_seguida.name, user_plaza_path(:id => plaza_seguida.id, :user_id => current_user.id) %></b></h5>
    				</li>
          <% end %>
  		  <% end %>
      <% end %>
  	</li>
  </ul>
</div>

app/views/shared/_ranks.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="/lista">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    seguidores
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    seguidos
  </a>
<div class="container"><h4>Usuarios recomendados</h4>
  <%= render @users %>
  </div>
  
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% @posts = Micropost.where(:user_id => current_user.id) %>
<% @peticiones = Micropost.where(:user_id => current_user.id).where(:petition => true) %>
<% @peticiones_all = Micropost.where(:petition => true) %>
<% @plazas_grupos = Group.where(:user_id => current_user.id) %>

<!--<div class="affix" style="width: 14%; max-width: 190px;">-->
	<section class="plaza_stats" style="margin-top: 0px; border: 1px solid #dddfe2; border-bottom: none;">
    <div>
      <div class="background_img"></div>
      <ul class="plaza_name_img">
        <li >
          <div class="plaza_img">
              <%= image_tag current_user.foto.url, class: "img-circle", size: 100  if current_user.foto? %> 
          </div>
        </li>
        <li style="text-align: center;">
          <div class="plaza_name">
            <h3 style="margin: 0px; font-weight: bolder; font-size: 22px;"><%= current_user.name if current_user.name? %></h3>
          </div>
        </li>
        <% if current_user.description? %>
        <li class="description"  style="text-align: center;">
          <%= current_user.description %>
        </li>
        <% end %>
      </ul>
    </div>
  </section>

<%
=begin%>
  <div class="aside_content" style="text-align: center;">
    <ul class="inline" style="margin-bottom: 0px;">
      <li class="titulo" >
        <%= link_to "Nueva consulta", '/petition', class: "btn btn-primary btn-sm", style: "padding: 5px; background-color: white; border: 1px solid #0084B4; color: #0084B4;" %>
      </li>
    </ul>
  </div>
<%
=end%>

  <div class="aside_content" style="">
    <ul class="principal">
      <li class="titulo" style="padding-bottom: 3px;">
        Comunidad
      </li>
      <li class="lista_block" style="color: #7e7e81;">
        <ul class="inline" style="width: 100%; text-align: center; ">
          <li style="width: 75%;">
            <i class="fa fa-users" aria-hidden="true"></i>
            &nbsp;<%= link_to current_user.followers.count, users_path(seguidores_id: current_user.id) %><span style="display: block; font-size: 12px;">Afiliados</span> 
          </li>
          <li style="width: 75%;">
            <i class="fa fa-user-o" aria-hidden="true"></i>
            &nbsp;<%= link_to current_user.following.count, users_path(seguidos_id: current_user.id) %><span style="display: block; font-size: 12px;">Apoya</span>
          </li>          
        </ul>
      </li>
      <li class="lista_block" style="color: #7e7e81;">
        <ul class="inline" style="width: 100%; text-align: center;">
          <li style="width: 32%;">
            <i class="fa fa-envelope-open-o" aria-hidden="true"></i> <%= @posts.where(:petition => true).count %>
          </li>
          <li style="width: 32%;">
            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
            <%= Vote.where(:micropost_id => @microposts).count %>
          </li>
          <li style="width: 32%;">
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <%= @plazas_grupos.count %>            
          </li> 
        </ul>
      </li>
    </ul>
  </div>
<!--</div>-->



<%
=begin%>
  <div class="aside_content">
    <ul class="principal">
      <li class="titulo">
        Comunidad
      </li>
      <li class="lista_block">
        <ul class="inline">
          <li>
            <i class="fa fa-user-o" aria-hidden="true"></i>   Seguidores
          </li>
          <li class="right">
            <a href="<%= followers_user_path(current_user) %>">
              <%= current_user.followers.count %>
            </a>
          </li>
        </ul>
      </li>
      <li class="lista_block">
        <ul class="inline">
          <li>
            <i class="fa fa-user-o" aria-hidden="true"></i>   Seguidos
          </li>
          <li class="right">
            <a href="<%= following_user_path(current_user) %>">
              <%= current_user.following.count %>
            </a>
          </li>
        </ul>
      </li>
      <li class="lista_block">
        <ul class="inline">
          <li>
            <i class="fa fa-envelope-open-o" aria-hidden="true"></i>   Iniciativas
          </li>
          <li class="right">
            <%= @posts.where(:petition => true).count %>
          </li>
        </ul>
      </li>
      <li class="lista_block">
        <ul class="inline">
          <li>
            <i class="fa fa-hand-o-up" aria-hidden="true"></i>   Votos recibidos totales
          </li>
          <li class="right">
            <%= Vote.where(:micropost_id => @microposts).count %>
          </li>
        </ul>
      </li>
      <li class="lista_block">
        <ul class="inline">
          <li style="width: 90%;">
            <i class="fa fa-circle-o" aria-hidden="true"></i>   Todos los círculos con los que colabora
          </li>
          <li class="right">
            <%= @plazas_grupos.count %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
<%
=end%>

<span class="badge"><%#  pluralize(current_user.microposts.count, "micropost") %></span>