config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get     '/lista',     to: "users#lista"
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to: 'static_pages#about'
  get     '/contact',   to: 'static_pages#contact'
  get     '/popular',   to: 'static_pages#popular'
  get     '/howtouse',   to: 'static_pages#howtouse'
  get     '/vision',    to: 'static_pages#vision'
  get     '/objetivos',    to: 'static_pages#objetivos'  
  get     '/candidate',    to: 'static_pages#candidate'   
  get     '/popular_last_day', to: 'static_pages#popular_last_day'
  get     '/signup',    to: 'users#new'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get     '/lista',     to: "users#lista"
  get     '/circles',   to: "users#following"
  get     '/new_plaza', to: 'users#new_plaza'
  get     '/plazas',    to: 'users#following_plaza'
  get     '/petition',  to: 'microposts#petition_form'
  get     '/micropost', to: 'microposts#show'
  get     '/petitions', to: 'microposts#petition_index'
  get     '/petitions_public', to: 'microposts#petition_index_public'
  post    '/plazas',            to: 'plazas#create'
  get     '/allplazas',         to: 'plazas#all_index'
  delete  '/dejardeseguir',     to: 'groups#destroy'
  post    '/seguir',            to: 'groups#create'
  get     '/popular',           to: 'static_pages#popular'
  get     '/index_municipios',  to: 'municipios#index'
  get     '/ir_a_tu_plaza',     to: 'plazas#show'

  resources :users do
    member do
      get :following, :followers
      get :edit_administrative
      put :update_administrative
      put :update_administrative_ciudad
      put :update_circles_administrative
    end

  resources :users do
    resources :users
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      get :hashtag
    end
  end
  resources :microposts do
    resources :comments do
      member do
        put :create
      end
    end
    resources :votes do
      member do
        put :update_like
        put :update_dislike
        put :update_circles_adminstrative
      end
    end
  end

  resources :users do
    resources :comments
    resources :plazas
    resources :groups
  end

  resources :plazas

  resources :municipios, only: [:index]
  
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
  <footer class="footer" style="position: relative; bottom: 10px; width: 100%; align-items: center;">
    <div class="col-xs-12 col-sm-6">
      <div class="col-xs-6">
        <ul class="list-space-s">
          <li>
            <h5>Acerca de</h5>
          </li>
          <li>
            <h6><%= link_to "Home", root_url %></h6>
          </li>
          <li>
            <a href="/about"><h6>Sobre polittizen</h6></a>
          </li>
          <li>
            <a href="/help"><h6>Ayuda / Contacto</h6></a>
          </li>          
        </ul>
      </div>
      <div class="col-xs-6">
        <ul class="list-space-s">
          <li>
            <h5>Ayuda</h5>
          </li>

          <li>
            <a href='/howtouse'><h6>Cómo usar polittizen</h6></a>
          </li>
          <li>
            <a href="/vision"><h6>Nuestra visión</h6></a>
          </li>
          <li>
            <a href="/objetivos"><h6>Objetivos</h6></a>
          </li>
          <li>
            <a href="/candidate"><h6>Candidatos</h6></a>
          </li>                              
        </ul>
      </div>      
    </div>
    <div class="col-xs-12 col-sm-6">
      
      <div class="col-xs-6">
        <ul class="list-space-s">
          <li>
            <h5>Redes sociales</h5>
          </li>
          <li>
            <a href="https://twitter.com/polittizen"><h6>Twitter</h6></a>
          </li>
          <li>
            <a href="https://www.facebook.com/polittizen"><h6>Facebook</h6></a>
          </li>
        </ul>
      </div>
      <div class="col-xs-6">
        <div style="margin-top: 20px; border: 3px solid #1DA1F2; border-radius: 15px; padding: 10px;">
          <h3 style="padding: 15px; color: green; margin: 0px; font-size: 13px;">polittizen 2018, por Roberto Villasevil Bargueño</h3>  
        </div>
      </div>
    </div>
  </div>

  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="margin-bottom: 0px;">
  <div class="container" style="padding: 0px;">
      <div class="icons_list">
        <% if logged_in? %>
          <ul class="icons">
            <li class="dropdown" style="width: 80%;">
              <%= link_to root_path do %>
                <div class="logo" style="display: inline-flex;">
                  <i class="fa fa-university fa-lg" aria-hidden="true" style="color: white;"></i>&nbsp;&nbsp;<h3 style="font-size: 18px; font-weight: lighter; font-family: 'Open Sans'; margin: 0px; color: white;"> polittizen</h3>
                </div>
              <% end %>               
            </li>
            <li class="dropdown">
              <%= link_to user_plazas_path(current_user) do %>
                <div>
                  <div class="icon_mobile">
                    <i class="fa fa-circle-o fa-lg" aria-hidden="true" style="color: white"></i>
                  </div>
                  <div class="icon_web">
                    <i class="fa fa-circle-o fa-lg" aria-hidden="true" style="color: white"></i>
                    <span class="logo"> Lobbies</span>
                  </div>
                </div>
              <% end %>
            </li>
            <li class="dropdown">
              <%= link_to '/lista' do %>              
                <div>
                  <div class="icon_mobile">
                    <i class="fa fa-university fa-lg" aria-hidden="true" style="color: white"></i>
                  </div>
                  <div class="icon_web">
                    <i class="fa fa-university fa-lg" aria-hidden="true" style="color: white"></i><span class="icon"> Candidatos</span>                      
                  </div>                 
                </div>
              <% end %>
            </li>
            <li class="dropdown">
              <%= link_to users_path do %>
                <div>
                  <div class="icon_mobile">
                    <i class="fa fa-users fa-lg" aria-hidden="true" style="color: white"></i>
                  </div>
                  <div class="icon_web">
                    <i class="fa fa-users fa-lg" aria-hidden="true" style="color: white"></i><span class="icon"> Polittizens</span>                     
                  </div>                  
                </div>
              <% end %>
            </li>
            <li class="dropdown">
              <%= link_to '/petitions' do %>
                <div>
                  <% @votos_petitions = Vote.where(micropost_id: current_user.feed_petition).where(user_id: current_user).count %>
                  <% @pendientes = current_user.feed_petition.count - @votos_petitions %>

                  <div class="icon_mobile">
                    <i class="fa fa-envelope-open fa-lg" aria-hidden="true" style="color: white"></i>
                    <% if @pendientes > 0 %>
                      <div style="background: red; border-radius: 0.8em; -moz-border-radius: 0.8em; -webkit-border-radius: 0.8em; color: white; display: inline-block; font-weight: bold; line-height: 1.6em; text-align: center; width: 1.6em; font-size: 12px; color: white; margin-left: -7px;">
                            <b><%= @pendientes %></b>
                      </div>
                    <% else %>
                      <div style="background: green; border-radius: 0.8em; -moz-border-radius: 0.8em; -webkit-border-radius: 0.8em; color: white; display: inline-block; font-weight: bold; line-height: 1.6em; text-align: center; width: 1.6em; font-size: 12px; color: white; margin-left: -7px;">
                            <b><%= @pendientes %></b>
                      </div>
                    <% end %>                    
                    
                  </div>
                  
                  <div class="icon_web">
                    <i class="fa fa-envelope-open fa-lg" aria-hidden="true" style="color: white"></i>
                    <% if @pendientes > 0 %>
                      <div style="background: red; border-radius: 0.8em; -moz-border-radius: 0.8em; -webkit-border-radius: 0.8em; color: white; display: inline-block; font-weight: bold; line-height: 1.6em; text-align: center; width: 1.6em; font-size: 12px; color: white; margin-left: -7px;">
                            <b><%= @pendientes %></b>
                      </div>
                    <% else %>
                      <div style="background: green; border-radius: 0.8em; -moz-border-radius: 0.8em; -webkit-border-radius: 0.8em; color: white; display: inline-block; font-weight: bold; line-height: 1.6em; text-align: center; width: 1.6em; font-size: 12px; color: white; margin-left: -7px;">
                            <b><%= @pendientes %></b>
                      </div>
                    <% end %>
                    <span class="icon"> Consultas</span>
                    
                                     
                  </div>                  
                </div>
              <% end %>
            </li>
            <li class="dropdown"> 
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">&nbsp;
                  <div class="icon_mobile" style="display: inline-flex;">
                    <i class="fa fa-user fa-lg" aria-hidden="true" style="color: white; margin-top: 5px;"></i>
                    &nbsp;<span class="icon"> You</span><b class="caret" style="display: inline-flex; color: white; margin-top: 10px;"></b>
                  </div>
              </a>

              <ul class="dropdown-menu" style="left: auto; right: 0px; font-family: 'Helvetica'; font-size: 14px; text-align: left;">
                <li style="text-align: left; margin-top: 10px;">
                  <%= link_to current_user do %>
                  <%= image_tag current_user.foto.url, class: "img-rounded", size: 20 if current_user.foto? %> <b>Perfil</b>
                  <% end %>
                </li>
                <li style="text-align: left; margin-top: 10px;">
                  <%= link_to edit_user_path(current_user) do %>
                  <i class="fa fa-cogs" aria-hidden="true" style="color: #1DA1F2;"></i> <b>Configuración</b>x
                  <% end %>
                </li>
                <li style="text-align: left; margin-top: 10px;">
                  <%= link_to user_plazas_path(current_user) do %>
                  <i class="fa fa-circle-o" aria-hidden="true" style="color: #1DA1F2;"></i> <b>Tus Lobbies</b>
                  <% end %>                    
                </li>                                            
                <li style="text-align: left; margin-top: 10px;">
                  <%= link_to edit_administrative_user_path( current_user), style: "color: #f4ac41;" do %>
                  <button type="button" class="btn btn-primary btn-sm" style="width: 100%; background-color: white; color: #0084B4; border: 3px solid #f4ac41; border-radius: 15px;">
                    <i class="fa fa-circle-o" aria-hidden="true" style="color: #f4ac41;"></i> Lobbies Administrativos
                  </button>
                  <% end %>                    
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to logout_path, method: "delete" do %>
                    <i class="fa fa-sign-out" aria-hidden="true"></i> <b>Salir</b>
                    <% end %>
                </li>
              </ul>
            </li>
        <% else %>
            <ul class="icons" style="padding-right: 30px; padding-left: 30px;">
              <li class="dropdown-home" style="width: 60%; padding-top: 12px; text-align: left;">
                <%= link_to root_path do %>                
                  <i class="fa fa-university fa-lg" style="color: white;"></i>&nbsp;&nbsp;
                  <span style="color: white; font-size: 18px; font-weight: lighter;">polittizen</span>
                <% end %>
              </li>
              <li class="dropdown-home" style="width: 20%;">
                <%= link_to login_path do %>
                    <span style="color: white">Login</span>
                <% end %>
              </li>
              <li class="dropdown-home" style="width: 20%;">
                <%= link_to signup_path do %>
                    <span style="color: white">Signup</span>
                <% end %>
              </li>
            </ul>
          </ul>
        <% end %>
      </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=PT+Serif"> -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

    <%= favicon_link_tag 'logo_blanco.png' %>

    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <div class="container" style="">
      <div class="row" style="">
        <div class="col-sm-12" style="margin-top: 10px;">
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>          
        </div>
      </div>
    </div>
  </body>
</html>